---
title: "Home Work 1"
author: "Lera"
date: '24 сентября 2018 г '
output: html_document
---
##Работа с данными
```{r}
data.df<-read.table("http://people.math.umass.edu/~anna/Stat597AFall2016/rnf6080.dat")
#Количество строк
nrow(data.df)

#Количество столбцов
ncol(data.df)

#Найдите значение из 5 строки седьмого столбца.
data.df[5,7]

#Напечатайте целиком 2 строку из data.df
data.df[2,]

#Данная функция присваивает именам  столбцов датафрейма значения year, mounth, day для первого, второго и третьего столбца соответственно,
#а остальным номера с 0 по 23
names(data.df) <- c("year", "month", "day", seq(0,23))

head(data.df)
tail(data.df)

data.df$daily<-rowSums(data.df[4:27])
hist(data.df$daily)

fixed.df<-read.table("http://people.math.umass.edu/~anna/Stat597AFall2016/rnf6080.dat")
fixed.df[,4:27][fixed.df[,4:27]<0]<-0
fixed.df$daily<-rowSums(fixed.df[4:27])
hist(fixed.df$daily)
#Данная гистограмма более коректна, потому что в ней нет отрицательных значений
```

##Синтаксис и типизирование
```{r}
#Для каждой строки кода поясните полученный результат, либо объясните почему она ошибочна.
v <- c("4", "8", "15", "16", "23", "42")
max(v)
sort(v)
#sum(v)

#Для следующих наборов команд поясните полученный результат, либо объясните почему они ошибочна.
v2 <- c("5",7,12)
#v2[2] + 2[3] - Ошибка! integer пытаемся использовать как вектор   

df3 <- data.frame(z1="5",z2=7,z3=12)
df3[1,2] + df3[1,3] #Сложение двух элементов датафрейма типа integer, ошибки нет

l4 <- list(z1="6", z2=42, z3="49", z4=126)
l4[[2]] + l4[[4]]
#l4[2] + l4[4]
l4[[2]]
```

##Работа с функциями и операторами
```{r}
#Числа от 1 до 10000 с инкрементом 372
seq(1,10000, by=372)

#Числа от 1 до 10000 длиной 50
seq(1,10000,length.out = 50)

#Объясните разницу
rep(1:5,times=3)
rep(1:5, each=3)
#Разница в том, что при использовании аргумента times - повторяется весь вектор times раз, а при использовании each - повторяется каждый элемент вектора each раз
```
