---
title: "R-intro"
author: "Lera"
date: '22 сентября 2018 г '
output: html_document
---

```{r echo=TRUE}
1234+4567
```

```{r}
29-45
```

```{r}
325/25
```
```{r}
56*12
```
```{r}
11*11
```

```{r}
111*111
```

```{r}
1111111*1111111
```

```{r}
options(width=40)
5:32
```

```{r}
1:10
```

```{r}
(1:10)+3
```

```{r}
(1:10)-3
```
```{r}
(1:10)*3
```

```{r}
(1:10)^2
```

```{r}
(1:10)^3
```

```{r}
3:4
```

```{r}
31%%7
```
```{r}
31%/%7
```
```{r}
7*4+3
```
```{r}
x <-c(4, 1, 8, 9)
y <-c(6, 2, 4, 3)
plot(x,y)
lines(x,y)
```
```{r}
x <- 1:10; y <- x^2;
plot(x,y)
lines(x,y)
```
```{r}
learn <-c("stats" = 15, "math"= 10,"programming" = 30, "attempts" = 45)
pie(learn)
barplot(learn)
```
```{r}
Z <- rnorm(1000)# 1000 standard normal random variates
hist(Z, prob = TRUE, main = "Гистограмма относительной частоты",
sub = "Плотность распределения")
curve(dnorm(x), from = -3, to = 3, add = TRUE, col = "blue")
```

```{r}
#Найдите площади примоугольников с длинами (3,7,12,15, 20) и ширинами (2, 5,8,11,15)
x<-c(3,7,12,15,20)
y<-c(2,5,8,11,15)
x*y
```

```{r}
#Постройте график этих длин и ширин
x<-c(3,7,12,15,20)
y<-c(2,5,8,11,15)
plot(x,y)
```

```{r echo=TRUE}
#Первокурсник Вася тратит очень мног овремени на домашнюю работу. 40 минут на математику, 40 на английский, 10 на физкультуру и 150 минут на программирование. Постройте график.
learn <-c("math" = 40, "english"= 40,"programming" = 150, "PE" = 10)
barplot(learn)
```
```{r echo=TRUE}
#Напитки разливаются вручную в банки по 455 мл, количество налитого нормально распределено со средним значением 450 мл. и стандартным отклонением 4 мл.
drinks<-rnorm(5,mean=450, sd=4)
drinks
drinks>455
#Смоделируйте разливание в 10000 бутылок и расчитайте вероятность переливания банки. 
drinks<-rnorm(1000,mean=450,sd=4)
z<-drinks>455
sum(z, na.rm=TRUE)/1000
```

