---
title: "Laboratory work"
author: "Lera"
date: '26 сентября 2018 г '
output: html_document
---

##Задание 1

```{r}
exp.1<-rexp(200)
var(exp.1,na.rm = TRUE) #среднее
sd(exp.1,na.rm = TRUE) #стандартное

#Повторите, использовав следующие значения параметра λ: 0.1, 0.5, 5, 10
exp.0.1<-rexp(200,rate = 0.1)
exp.0.5<-rexp(200,rate = 0.5)
exp.5<-rexp(200, rate = 5)
exp.10<-rexp(200,rate = 10)

#Используйте функцию hist() для построения гистограммы полученного ранее стандартного распределения
#hist(exp.1)

#Используйте функцию plot() с тем же самым вектором для построения графика значений в порядке следования.
#plot(exp.1)

#Используйте функцию plot() с любыми двумя полученными ранее векторами, чтобы получить диаграмму рассеяния  этих векторов относительно друг друга
#plot(exp.1,exp.10)

#вектор, содержащий средние значения каждого из 5 полученных ранее распределений в порядке их создания
exp.means<-c(mean(exp.1),mean(exp.0.1),mean(exp.0.5),mean(exp.5),mean(exp.10))
exp.means
#Гистограммы:
#Вектор с пятью средними относительно каждого из пяти векторов с различными значениями λ
plot(rep(exp.means,times=length(exp.1)/length(exp.means)),exp.1)

```

##Задание 2
```{r}
huge.exp.1<-rexp(1100000)
var(huge.exp.1,na.rm = TRUE) #среднее
sd(huge.exp.1,na.rm = TRUE) #стандартное

#Получите гистограмму huge.exp.1.
#hist(huge.exp.1) #соответствует графику, должна

#Получите среднее всех чисел из huge.exp.1 строго больших 1
exp.greater.1<-huge.exp.1[huge.exp.1>1]
mean(exp.greater.1)

#Проверка созданного вектора, все ли числа в нем больше 1
if(sum(exp.greater.1>1, na.rm=FALSE)==length(exp.greater.1)){
  print("Выборка верна")
} else {
  print("Выборка ошибочна")
}

#Получите матрицу huge.exp.1.mat, содержащую 1100 строк и 1000 колонок.
huge.exp.1.mat<-matrix(huge.exp.1,nrow = 1100,ncol = 1000)

#Постройте гистограмму, использовав полученную матрицу
#hist(huge.exp.1.mat)

#Рассчитайте среднее 137-й колонки из huge.exp.1.mat.
mean(huge.exp.1.mat[,137])

#Найдите среднее всей 1000 колонок и сохраните их в вектор
col.mean<-colMeans(huge.exp.1.mat)

#Отобразите диаграмму средних зннчений колонок.
#hist(col.mean)

#Рассчитайте квадрат каждого значения из huge.exp.1 и найдите среднее и стандартное отклонение полученного вектора квадратов.
sqrt.huge.exp.1<-huge.exp.1^2
var(sqrt.huge.exp.1,na.rm = TRUE) #среднее
sd(sqrt.huge.exp.1,na.rm = TRUE) #стандартное

```

